services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NEXT_PUBLIC_API_URL: "https://shorten-url-api-backend-prod.onrender.com"
    command: npm run dev
